const fs=require('fs');
const path=require('path');
const Module=require('module');
const indexPath=path.join(__dirname,'index.js');
let source=fs.readFileSync(indexPath,'utf8');

const BASES=['Candy','Lava','Galaxy','Yin Yang','Radioactive','Cursed','Divine','Cyber','Phantom','Crystal'];
source=source.replace(/const mutationBases=\[[\s\S]*?\];\nconst baseFiles=\{[\s\S]*?\};/,`const mutationBases=${JSON.stringify(BASES)};const baseFiles=Object.fromEntries(mutationBases.map(b=>[b,b+'Base.png']));`);
source=source.replace(/const mmValues=\[[\s\S]*?\];/,`const mmValues=[['10M - 250M','Middleman for trades from 10M to 250M'],['250M - 500M','Middleman for trades from 250M to 500M'],['500M - 1B','Middleman for trades from 500M to 1B'],['1B - 5B','Middleman for trades from 1B to 5B'],['5B+','Middleman for trades worth 5B+'],['OG / Rare Items','OG / rare-item trade']];`);
source=source.replace(/function mmMenu\(\)\{[\s\S]*?\n\}/,`function mmMenu(){return row(new StringSelectMenuBuilder().setCustomId('fsmm_mm_pick_v3').setPlaceholder('Select trade value...').addOptions(mmValues.map(([label,description])=>({label,value:label,description}))))}`);
source=source.replace(/function mutationMenu\(\)\{[\s\S]*?\n\}/,`function mutationMenu(){return row(new StringSelectMenuBuilder().setCustomId('fsmm_base_pick_v3').setPlaceholder('🎨 Select a base to paint...').addOptions(mutationBases.map(b=>({label:b,value:b,description:\`${b} Base • FSMM painting\`}))))}`);
source=source.replace(/function panelConfigs\(\)\{[\s\S]*?\n\}/,`function panelConfigs(){return [['🤝・middleman',embed('🤝 FSMM MIDDLEMAN','Need a safe middleman?\\n\\nSelect your trade value below, then tell us what **you** are giving and what **the other trader** is giving.'),mmMenu()],['🛟・support',embed('🛟 FSMM SUPPORT','Choose what you need: **Host a Giveaway**, **Claim a Giveaway**, **Report**, or **Apply for a Role**.'),supportMenu()],['🎨・base-painting',embed('🎨 FSMM BASE PAINTING','Choose your base from **Candy → Crystal**. You will then be asked for your Roblox username, **payment**, and **collateral**.'),mutationMenu()]]}`);
source=source.replace(/async function upsertPanel\(channel,e,components\)\{[\s\S]*?\n\}/,`async function upsertPanel(channel,e,components){const messages=await channel.messages.fetch({limit:50}).catch(()=>null);const bots=messages?[...messages.values()].filter(m=>m.author?.id===client.user.id):[];const title=e.data?.title;const panel=bots.find(m=>m.embeds?.[0]?.title===title)||bots.find(m=>m.components?.length>0);if(panel)return panel.edit({embeds:[e],components:[components],allowedMentions:{parse:[]}});return channel.send({embeds:[e],components:[components],allowedMentions:{parse:[]}})}`);

const formPatch=`
function fsmmMMModalV3(value){const m=new ModalBuilder().setCustomId('fsmm_mm_modal_v3:'+encodeURIComponent(value)).setTitle('FSMM Middleman Request');const a=new TextInputBuilder().setCustomId('you').setLabel('What are YOU giving?').setStyle(TextInputStyle.Paragraph).setRequired(true).setMaxLength(900);const b=new TextInputBuilder().setCustomId('their').setLabel('What is the OTHER TRADER giving?').setStyle(TextInputStyle.Paragraph).setRequired(true).setMaxLength(900);const c=new TextInputBuilder().setCustomId('other').setLabel('Other trader username').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(100);const d=new TextInputBuilder().setCustomId('tip').setLabel('What are you tipping?').setStyle(TextInputStyle.Short).setRequired(false).setMaxLength(300);return m.addComponents(row(a),row(b),row(c),row(d))}
function fsmmPaintModalV3(base){const m=new ModalBuilder().setCustomId('fsmm_paint_modal_v3:'+encodeURIComponent(base)).setTitle(base+' Base Painting');const a=new TextInputBuilder().setCustomId('roblox').setLabel('Roblox username').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(100);const b=new TextInputBuilder().setCustomId('payment').setLabel('What is your payment?').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(300);const c=new TextInputBuilder().setCustomId('collateral').setLabel('What is your collateral?').setStyle(TextInputStyle.Paragraph).setRequired(true).setMaxLength(500);const d=new TextInputBuilder().setCustomId('notes').setLabel('Extra details (optional)').setStyle(TextInputStyle.Paragraph).setRequired(false).setMaxLength(900);return m.addComponents(row(a),row(b),row(c),row(d))}
client.on('interactionCreate',async i=>{try{if(i.isStringSelectMenu()&&i.customId==='fsmm_base_pick_v3'){const b=i.values[0];if(!mutationBases.includes(b))return i.reply({content:'❌ Invalid base.',flags:MessageFlags.Ephemeral});return i.showModal(fsmmPaintModalV3(b))}if(i.isStringSelectMenu()&&i.customId==='fsmm_mm_pick_v3'){return i.showModal(fsmmMMModalV3(i.values[0]))}if(i.isModalSubmit()&&i.customId.startsWith('fsmm_paint_modal_v3:')){const b=decodeURIComponent(i.customId.slice('fsmm_paint_modal_v3:'.length));return createTicket(i,'basepainting',{base:b,roblox:i.fields.getTextInputValue('roblox'),payment:i.fields.getTextInputValue('payment'),collateral:i.fields.getTextInputValue('collateral'),notes:i.fields.getTextInputValue('notes')})}if(i.isModalSubmit()&&i.customId.startsWith('fsmm_mm_modal_v3:')){const v=decodeURIComponent(i.customId.slice('fsmm_mm_modal_v3:'.length));return createTicket(i,'middleman',{value:v,you:i.fields.getTextInputValue('you'),their:i.fields.getTextInputValue('their'),other:i.fields.getTextInputValue('other'),tip:i.fields.getTextInputValue('tip')})}}catch(e){console.error('[FSMM V3]',e);if(!i.replied&&!i.deferred)await i.reply({content:'❌ Something went wrong. Please try again.',flags:MessageFlags.Ephemeral}).catch(()=>{})}});
`;
const login='client.login(TOKEN);';
const p=source.indexOf(login);if(p<0)throw new Error('FSMM login marker missing');
source=source.slice(0,p)+formPatch+`\nlet fsmmPanelsRefreshed=false;async function fsmmRefreshPanels(){if(fsmmPanelsRefreshed)return;fsmmPanelsRefreshed=true;try{const g=client.guilds.cache.get(GUILD_ID);if(!g)throw new Error('Guild not found in client cache');console.log('[FSMM V3] refreshing panels...');await setup(g);console.log('[FSMM V3] PANELS AUTO-REFRESHED')}catch(e){fsmmPanelsRefreshed=false;console.error('[FSMM V3] PANEL REFRESH ERROR:',e)}}\nclient.once('clientReady',fsmmRefreshPanels);client.once('ready',fsmmRefreshPanels);setTimeout(()=>fsmmRefreshPanels(),15000);\n`+source.slice(p);

const ticketPatch=`if(d.value)e.addFields({name:'💰 Trade Value',value:safe(d.value,50),inline:true});if(d.you)e.addFields({name:'👤 You',value:safe(d.you,900)});if(d.their)e.addFields({name:'👤 Other Trader',value:safe(d.their,900)});if(d.other)e.addFields({name:'👤 Other Trader Username',value:safe(d.other,100),inline:true});if(d.tip)e.addFields({name:'🎁 Tip',value:safe(d.tip,300),inline:true});if(d.payment)e.addFields({name:'💳 Payment',value:safe(d.payment,300),inline:true});if(d.collateral)e.addFields({name:'🛡️ Collateral',value:safe(d.collateral,500),inline:true});if(d.notes)e.addFields({name:'📝 Details',value:safe(d.notes,900)});if(d.roblox)e.addFields({name:'🎮 Roblox Username',value:safe(d.roblox,100),inline:true});if(d.supportType)e.addFields({name:'📌 Request Type',value:safe(d.supportType,100),inline:true});if(d.base){e.addFields({name:'🎨 Base Requested'`;
source=source.replace(/if\(d\.value\)e\.addFields\([\s\S]*?if\(d\.base\)\{e\.addFields\(\{name:'🎨 Base Requested'/,ticketPatch);

const compiled=new Module(indexPath,module.parent);compiled.filename=indexPath;compiled.paths=Module._nodeModulePaths(path.dirname(indexPath));console.log('[FSMM V3] boot2 loading patched index.js');compiled._compile(source,indexPath);
