require('dotenv').config();
const path=require('path');
const {Client,REST,EmbedBuilder}=require('discord.js');
const DATA=path.join(__dirname,'..','data','craft-live.json');
const CURRENT=`http://127.0.0.1:${process.env.PORT||3000}/craft/current`;
const RECIPES={'Bandito Axolito':['1x Bandito Bobritto','1x Trulimero Trulicina','2x Chef Crabracadabra'],'Electro Quacko':['1x Strawberreli Flamingelli','1x Burbaloni Loliloli','1x Chimpanzini Bananini'],'Sigma Girl':['3x Bambini Crostini','1x Sigma Boy'],'Los Noobinis':['3x Noobini Pizzanini','1x Tracoducotulu Delapeladustuz'],'Bee Loco':['1x Sigma Boy','1x Quivioli Ameleonni','1x Te Te Te Sahur','1x Frigo Camelo'],'Koala Parabala':['1x Trenostruzzo Turbo 3000','1x Girafa Celestre','1x Cocofanto Elefanto'],'Orcalita Orcala':['1x Orcalero Orcala','1x Tralalita Tralala','2x Girafa Celestre'],'Squalanana':['1x Bananito Bandito','1x Orangutini Ananassini','1x Tractoro Dinosauro'],'Hippo Jacuzzo':['1x Aquanaut','2x Tralalero Tralala'],'Pelican Pachetto':['1x Appelini','1x Graipuss Medussi','1x Los Tralaleritos'],'Deputy Leopard':['1x La Grande Combinasion','1x Sir Mangus','1x Gub'],'Chicli Chicla':['1x Tang Tang Keletang','1x Los Chicleteiras','1x Bananito'],'Panda Popanda':['1x DJ Panda','1x Candini Fluffini'],'La Craft Machine':['1x Fragola La La La','1x Celularcini Viciosini','1x Las Sis','1x La Sahur Combinasion'],'Gold and Diamond':['1x Gold Gold Gold','1x Gym Bros','1x Chillin Chili'],'Los Dragons':['1x Dragon Cannelloni','1x Dragon Gingerini','1x Dragon Aquanini']};
const TIMES={'Bandito Axolito':'15m','Electro Quacko':'15m','Sigma Girl':'30m','Los Noobinis':'30m','Bee Loco':'30m','Koala Parabala':'45m','Orcalita Orcala':'45m','Squalanana':'45m','Hippo Jacuzzo':'45m','Pelican Pachetto':'1h30m','Deputy Leopard':'1h30m','Chicli Chicla':'1h30m','Panda Popanda':'1h30m','La Craft Machine':'1h30m','Gold and Diamond':'1h30m','Los Dragons':'1h30m'};
async function live(){try{const r=await fetch(CURRENT);if(!r.ok)return null;const j=await r.json();return Array.isArray(j.items)&&j.items.length>=5?j.items.slice(0,5):null}catch{return null}}
function patchREST(){const old=REST.prototype.put;REST.prototype.put=function(route,opts,...rest){try{if(opts?.body&&Array.isArray(opts.body)){const has=opts.body.some(c=>c?.name==='craft');const body=has?opts.body.map(c=>c?.name==='craft'?{...c,description:'View Craft Machine recipes and the verified live rotation'}:c):[...opts.body,{name:'craft',description:'View Craft Machine recipes and the verified live rotation',type:1,options:[]}];opts={...opts,body}}}catch(e){console.error('[CRAFT CMD] command patch:',e.message)}return old.call(this,route,opts,...rest)}}
function catalog(){const e=new EmbedBuilder().setTitle('🛠️ FSMM CRAFT MACHINE').setColor(0x5865f2).setDescription('Current OG Craft recipe catalogue. The in-game machine rotates **5 recipes every 30 minutes**.');const n=Object.keys(RECIPES);for(let i=0;i<n.length;i+=4)e.addFields({name:`Recipes ${i+1}–${Math.min(i+4,n.length)}`,value:n.slice(i,i+4).map(x=>`**${x}** — ${RECIPES[x].join(', ')}`).join('\n')});return e}
function liveEmbed(items){const e=new EmbedBuilder().setTitle('🔄 CRAFT MACHINE — LIVE ROTATION').setColor(0x57f287).setDescription('Verified rotation received by the FSMM collector.');for(const x of items){const req=x.requirements||x.recipe||RECIPES[x.name]||['Recipe unavailable'];e.addFields({name:`🧠 ${x.name}`,value:`**Recipe:** ${Array.isArray(req)?req.join('\n'):String(req)}\n**Time:** ${x.time||TIMES[x.name]||'Unknown'}`})}return e}
function patchClient(){const old=Client.prototype.emit;Client.prototype.emit=function(event,...args){if(event==='interactionCreate'){const i=args[0];if(i?.isChatInputCommand?.()&&i.commandName==='craft'){(async()=>{const items=await live();return i.reply({embeds:[items?liveEmbed(items):catalog()]})})().catch(e=>{console.error('[CRAFT CMD]',e);if(!i.replied&&!i.deferred)i.reply({content:'❌ Craft command failed.',ephemeral:true})});return true}}return old.call(this,event,...args)}}
patchREST();patchClient();
