'use strict';
require('dotenv').config();
const fs=require('fs');const path=require('path');
const {Client,EmbedBuilder}=require('discord.js');
const DATA_FILE=process.env.EXIST_DATA_FILE||path.join(__dirname,'..','data','exist-store.json');
const SOURCE='https://sabexistcount.com/sab-exist-count-list';
const SYNC_MS=6*60*60*1000;
const DATA_VERSION=3;
function httpGet(url){return new Promise((resolve,reject)=>{const https=require('https');const req=https.get(url,{headers:{'User-Agent':'Mozilla/5.0 FSMM-Exist/5.0',Accept:'text/html,application/xhtml+xml'}},res=>{if(res.statusCode>=300&&res.statusCode<400&&res.headers.location){res.resume();return resolve(httpGet(new URL(res.headers.location,url).toString()));}if(res.statusCode!==200){res.resume();return reject(new Error(`HTTP ${res.statusCode}`));}const chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>resolve(Buffer.concat(chunks).toString('utf8')));});req.setTimeout(15000,()=>req.destroy(new Error('request timeout')));req.on('error',reject);});}
function cleanHtml(s){return String(s||'').replace(/<script[\\s\\S]*?<\\/script>/gi,' ').replace(/<style[\\s\\S]*?<\\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&nbsp;/g,' ').replace(/\\s+/g,' ').trim();}
function slugify(name){return String(name).normalize('NFKD').replace(/[\\u0300-\\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'-').replace(/^-|-$/g,'').toLowerCase();}
function hasKnownCount(v){const s=String(v||'').trim();return !!s&&s!=='—'&&s!=='-'&&!/^unknown$/i.test(s)&&!/^n\\/a$/i.test(s)&&/\\d/.test(s);}
function parseRows(html){const items=[];for(const row of html.match(/<tr[\\s\\S]*?<\\/tr>/gi)||[]){const cells=[...row.matchAll(/<t[dh][^>]*>([\\s\\S]*?)<\\/t[dh]>/gi)].map(m=>cleanHtml(m[1]));if(cells.length<3||/^brainrot$/i.test(cells[0]))continue;const name=cells[0].replace(/\\s+(Common|Rare|Epic|Legendary|Mythic|Brainrot God|Secret|OG|Other)$/i,'').trim();const rarity=cells[1]||'Unknown';const exist=cells[2]||'';if(!name||name.length>100||!hasKnownCount(exist))continue;items.push({name,rarity,exist,slug:slugify(name)});}return [...new Map(items.map(x=>[x.name.toLowerCase(),x])).values()];}
function load(){try{return JSON.parse(fs.readFileSync(DATA_FILE,'utf8'));}catch{return {items:[],syncedAt:0,version:0};}}
let db=load();if(!Array.isArray(db.items))db.items=[];
function save(){try{fs.mkdirSync(path.dirname(DATA_FILE),{recursive:true});const tmp=DATA_FILE+'.tmp';fs.writeFileSync(tmp,JSON.stringify(db,null,2));fs.renameSync(tmp,DATA_FILE);}catch(e){console.error('[FSMM EXIST] save:',e.message);}}
async function sync(){try{const html=await httpGet(SOURCE);const items=parseRows(html);if(!items.length)throw new Error('No known exist counts parsed from source');db={items,syncedAt:Date.now(),version:DATA_VERSION};save();console.log(`[FSMM EXIST] cached ${items.length} Brainrots with known exist counts`);}catch(e){console.error('[FSMM EXIST] sync failed:',e.message);}}
function find(name){const q=String(name||'').toLowerCase().trim();return db.items.find(x=>x.name.toLowerCase()===q)||db.items.find(x=>x.name.toLowerCase().includes(q));}
const fmt=v=>String(v||'Unknown').replace(/\\s+/g,' ').trim();
function embed(item){return new EmbedBuilder().setTitle(`🧠 ${item.name}`).setDescription(`**Rarity:** ${fmt(item.rarity)}\\n\\n📊 **Known Exist Count:** **${fmt(item.exist)}**\\n\\nOnly Brainrots with an actual known exist count are included in FSMM.`).setColor(0x5865f2).setFooter({text:`FSMM Exist • ${db.items.length} known counts`});}
const originalLogin=Client.prototype.login;
Client.prototype.login=function(...args){const client=this;if(!client.__fsmmExistAttached){client.__fsmmExistAttached=true;client.on('interactionCreate',async i=>{try{if(!i.isChatInputCommand()||i.commandName!=='exist'||!i.guild)return;await i.deferReply();const item=find(i.options.getString('brainrot'));if(!item)return i.editReply('❌ This Brainrot does not have a known exist count in the FSMM database.');return i.editReply({embeds:[embed(item)]});}catch(e){console.error('[FSMM EXIST] interaction:',e.message);if(i.deferred||i.replied)i.editReply('⚠️ Exist data is temporarily unavailable.').catch(()=>null);}});client.once('clientReady',()=>{if(db.version!==DATA_VERSION||!db.items.length||Date.now()-(db.syncedAt||0)>SYNC_MS)sync();setInterval(sync,SYNC_MS).unref();});}return originalLogin.apply(this,args);};
