'use strict';
require('dotenv').config();
const fs=require('fs');
const path=require('path');
const https=require('https');
const {Client,EmbedBuilder}=require('discord.js');
const DATA_FILE=process.env.EXIST_DATA_FILE||path.join(__dirname,'..','data','exist-store.json');
const SOURCE='https://sabexistcount.com/wiki/all-brainrots';
const PRODUCT_BASE='https://sabexistcount.com/products/';
const SYNC_MS=6*60*60*1000;
function httpGet(url){return new Promise((resolve,reject)=>{const req=https.get(url,{headers:{'User-Agent':'FSMM-Exist/2.0',Accept:'text/html,application/xhtml+xml'}},res=>{if(res.statusCode>=300&&res.statusCode<400&&res.headers.location){res.resume();return resolve(httpGet(new URL(res.headers.location,url).toString()));}if(res.statusCode!==200){res.resume();return reject(new Error(`HTTP ${res.statusCode}`));}const chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>resolve(Buffer.concat(chunks).toString('utf8')));});req.setTimeout(12000,()=>req.destroy(new Error('request timeout')));req.on('error',reject);});}
function cleanHtml(s){return String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim();}
function slugify(name){return String(name).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'-').replace(/^-|-$/g,'').toLowerCase();}
function parseRows(html){const items=[];for(const row of html.match(/<tr[\s\S]*?<\/tr>/gi)||[]){const cells=[...row.matchAll(/<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/gi)].map(m=>cleanHtml(m[1]));if(cells.length<5||cells[0].toLowerCase()==='brainrot')continue;const name=cells[0].replace(/\s+(Common|Rare|Epic|Legendary|Mythic|Brainrot God|Secret|OG|Other)$/i,'').trim();if(!name||name.length>100)continue;items.push({name,rarity:cells[1]||'Unknown',income:cells[3]||'Unknown',exist:cells[4]||'Unknown',slug:slugify(name)});}return [...new Map(items.map(x=>[x.name.toLowerCase(),x])).values()];}
function load(){try{return JSON.parse(fs.readFileSync(DATA_FILE,'utf8'));}catch{return {items:[],syncedAt:0};}}
let db=load();if(!Array.isArray(db.items))db.items=[];
function save(){try{fs.mkdirSync(path.dirname(DATA_FILE),{recursive:true});const tmp=DATA_FILE+'.tmp';fs.writeFileSync(tmp,JSON.stringify(db,null,2));fs.renameSync(tmp,DATA_FILE);}catch(e){console.error('[FSMM EXIST] save:',e.message);}}
async function sync(){try{const items=parseRows(await httpGet(SOURCE));if(!items.length)throw new Error('No Brainrots parsed');db.items=items;db.syncedAt=Date.now();save();console.log(`[FSMM EXIST] cached ${items.length} Brainrots`);}catch(e){console.error('[FSMM EXIST] sync failed:',e.message);}}
function find(name){const q=String(name||'').toLowerCase().trim();return db.items.find(x=>x.name.toLowerCase()===q)||db.items.find(x=>x.name.toLowerCase().includes(q));}
function format(v){return String(v||'Unknown').replace(/\s+/g,' ').trim();}
async function getMutations(item){if(item.cachedMutations&&typeof item.cachedMutations==='object')return item.cachedMutations;try{const text=cleanHtml(await httpGet(`${PRODUCT_BASE}${item.slug}`));const section=text.match(/Mutations\s+Variant\s+Exist Count[\s\S]*?(?:Trivia|About|FAQ)/i)?.[0]||'';const out={};for(const m of section.matchAll(/\b(Normal|Radioactive|Bloodrot|Candy|Crystal|Cursed|Default|Diamond|Galaxy|Gold|Lava|Rainbow|Yin Yang|Cyber|Divine|Phantom)\s+(\d[\d,.]*(?:K|M|B|T)?(?:\s*\([^)]*\))?|—)/gi))if(!out[m[1]])out[m[1]]=m[2];item.cachedMutations=out;save();return out;}catch(e){return {};}}
function embed(item,mutations){const lines=Object.entries(mutations).filter(([n])=>n!=='Normal'||format(mutations[n])!==format(item.exist)).slice(0,8).map(([n,c])=>`🧬 **${n}** — ${format(c)}`);return new EmbedBuilder().setTitle(`🧠 ${item.name}`).setDescription(`**${item.rarity}** • **${item.income}**\n\n📊 **Known Exist Count:** **${format(item.exist)}**${lines.length?`\n\n**Mutations**\n${lines.join('\n')}`:''}`).setColor(0x5865f2).setFooter({text:`FSMM Exist • Cached data • ${db.items.length} items`});}
const originalLogin=Client.prototype.login;
Client.prototype.login=function(...args){const client=this;if(!client.__fsmmExistAttached){client.__fsmmExistAttached=true;client.on('interactionCreate',async i=>{try{if(i.isAutocomplete()&&i.commandName==='exist'){const q=(i.options.getString('brainrot')||'').toLowerCase();return i.respond(db.items.filter(x=>!q||x.name.toLowerCase().includes(q)).slice(0,25).map(x=>({name:`${x.name} • ${x.exist}`,value:x.name}))).catch(()=>null);}if(!i.isChatInputCommand()||i.commandName!=='exist'||!i.guild)return;await i.deferReply();const item=find(i.options.getString('brainrot'));if(!item)return i.editReply('❌ Brainrot not found in the cached FSMM database.');const mutations=await getMutations(item);return i.editReply({embeds:[embed(item,mutations)]});}catch(e){console.error('[FSMM EXIST] interaction:',e.message);if(i.deferred||i.replied)i.editReply('⚠️ Exist data is temporarily unavailable.').catch(()=>null);}});client.once('clientReady',async()=>{if(!db.items.length||Date.now()-(db.syncedAt||0)>SYNC_MS)await sync();setInterval(sync,SYNC_MS).unref();});}return originalLogin.apply(this,args);};
