require('dotenv').config();
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {Client,REST,PermissionFlagsBits,EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,ModalBuilder,TextInputBuilder,TextInputStyle,ChannelType}=require('discord.js');
const FILE=process.env.GIVEAWAY_DATA_FILE||path.join(__dirname,'..','data','giveaways.json');
const state={giveaways:{}};
try{if(fs.existsSync(FILE))Object.assign(state,JSON.parse(fs.readFileSync(FILE,'utf8')))}catch(e){console.error('[GIVEAWAY] load:',e.message)}
function save(){fs.mkdirSync(path.dirname(FILE),{recursive:true});const tmp=FILE+'.tmp';fs.writeFileSync(tmp,JSON.stringify(state,null,2));fs.renameSync(tmp,FILE)}
function clean(v,n=500){return String(v??'').replace(/@everyone|@here/gi,'@ mention').replace(/[\u0000-\u001F\u007F]/g,' ').trim().slice(0,n)||'Not provided'}
function staff(i){return !!i.guild&&(i.guild.ownerId===i.user.id||i.memberPermissions?.has(PermissionFlagsBits.ManageGuild)||i.memberPermissions?.has(PermissionFlagsBits.ManageMessages)||i.member?.roles?.cache?.some(r=>['FSMM Staff','Owner','Moderator'].includes(r.name)))}
function entryRow(id,ended=false){return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`fsmm_gw_join:${id}`).setLabel(ended?'Event Ended':'Enter Event').setEmoji('🎉').setStyle(ButtonStyle.Success).setDisabled(ended),new ButtonBuilder().setCustomId(`fsmm_gw_leave:${id}`).setLabel('Leave').setEmoji('🚪').setStyle(ButtonStyle.Secondary).setDisabled(ended))}
function hostRow(id,ended=false){return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`fsmm_gw_finish:${id}`).setLabel(ended?'Declare Winner':'End & Review Winner').setStyle(ButtonStyle.Primary).setDisabled(ended&&false),new ButtonBuilder().setCustomId(`fsmm_gw_cancel:${id}`).setLabel('Cancel').setStyle(ButtonStyle.Danger).setDisabled(ended))}
function embed(g){const end=g.ended?`Ended <t:${Math.floor((g.endedAt||Date.now())/1000)}:R>`:`Ends <t:${Math.floor(g.endsAt/1000)}:R>`;const role=g.requiredRoleId?`<@&${g.requiredRoleId}>`:'Everyone';const winners=g.winnerIds?.length?g.winnerIds.map(x=>`<@${x}>`).join(', '):'Pending';return new EmbedBuilder().setTitle('🎉 FSMM COMMUNITY REWARD').setDescription(`## ${clean(g.prize,250)}\n\n🎟️ **Entries:** ${g.entries.length}\n🏆 **Winner${g.winners>1?'s':''}:** ${winners}\n👥 **Required role:** ${role}\n⏱️ **${end}**\n\nClick **Enter Event** to join. You can leave before it ends.`).setColor(0x5865f2).setFooter({text:`Hosted by ${g.hostTag} • FSMM`}).setTimestamp(new Date(g.createdAt))}
async function update(client,g,components){try{const ch=await client.channels.fetch(g.channelId);const m=await ch.messages.fetch(g.messageId);await m.edit({embeds:[embed(g)],components});}catch(e){console.error('[GIVEAWAY] update:',e.message)}}
async function announce(client,g,text){const ch=await client.channels.fetch(g.channelId).catch(()=>null);if(ch)await ch.send({content:text})}
async function audit(client,g,text){try{const ch=g.guildId&&await client.channels.fetch(g.logChannelId||'').catch(()=>null);if(ch)await ch.send({embeds:[new EmbedBuilder().setTitle('🛡️ Reward Event Audit').setDescription(text).setColor(0x5865f2)]})}catch{}}
function schedule(client,g){if(g.ended||g.cancelled)return;const wait=Math.max(1000,g.endsAt-Date.now());setTimeout(async()=>{if(!g.ended&&!g.cancelled){g.ended=true;g.endedAt=Date.now();save();await update(client,g,[entryRow(g.id,true),hostRow(g.id,true)]);await announce(client,g,`⏰ **Event ended.**\nReward: **${clean(g.prize,250)}**\nEntries: **${g.entries.length}**\nA staff/host review is required to declare the eligible winner${g.winners>1?'s':''}.`) }},wait)}
function patchREST(){const old=REST.prototype.put;REST.prototype.put=function(route,options,...rest){try{if(options?.body&&Array.isArray(options.body))options={...options,body:options.body.map(c=>c?.name==='giveaway'?{...c,description:'Create a transparent FSMM community reward event',default_member_permissions:PermissionFlagsBits.ManageGuild.toString(),options:[{type:4,name:'minutes',description:'Duration in minutes',required:true,min_value:1,max_value:10080},{type:3,name:'prize',description:'Reward description',required:true,max_length:250},{type:4,name:'winners',description:'Number of winners',required:false,min_value:1,max_value:10},{type:7,name:'channel',description:'Event channel',required:false,channel_types:[ChannelType.GuildText,ChannelType.GuildAnnouncement]},{type:8,name:'required_role',description:'Role required to enter',required:false}]}:c)}}catch(e){console.error('[GIVEAWAY] command patch:',e.message)}return old.call(this,route,options,...rest)}}
async function create(client,i){if(!staff(i))return i.reply({content:'❌ Staff only.',ephemeral:true});const minutes=i.options.getInteger('minutes',true),prize=clean(i.options.getString('prize',true),250),winners=i.options.getInteger('winners')||1,role=i.options.getRole('required_role'),channel=i.options.getChannel('channel')||i.channel;if(!channel?.isTextBased())return i.reply({content:'❌ Choose a text channel.',ephemeral:true});const id=crypto.randomUUID(),logChannel=i.guild.channels.cache.find(c=>c.isTextBased()&&['server-logs','fsmm-logs'].includes(c.name));const g={id,guildId:i.guild.id,channelId:channel.id,logChannelId:logChannel?.id||null,prize,winners,requiredRoleId:role?.id||null,hostId:i.user.id,hostTag:i.user.tag,createdAt:Date.now(),endsAt:Date.now()+minutes*60000,entries:[],ended:false,cancelled:false,winnerIds:[]};const m=await channel.send({embeds:[embed(g)],components:[entryRow(id),hostRow(id)]});g.messageId=m.id;state.giveaways[id]=g;save();schedule(client,g);return i.reply({content:`✅ Reward event created in ${channel}.\n• Reward: **${prize}**\n• Duration: **${minutes}m**\n• Winners: **${winners}**`,ephemeral:true})}
async function button(client,i){const [action,id]=i.customId.split(':');const g=state.giveaways[id];if(!g)return i.reply({content:'❌ Event not found.',ephemeral:true});if(action==='fsmm_gw_join'||action==='fsmm_gw_leave'){if(g.ended||g.cancelled)return i.reply({content:'❌ This event is no longer accepting entries.',ephemeral:true});if(g.requiredRoleId&&!i.member.roles.cache.has(g.requiredRoleId))return i.reply({content:'❌ You do not have the required role.',ephemeral:true});const idx=g.entries.indexOf(i.user.id);if(action==='fsmm_gw_join'){if(idx!==-1)return i.reply({content:'ℹ️ You are already entered.',ephemeral:true});g.entries.push(i.user.id);save();return i.update({embeds:[embed(g)],components:[entryRow(id),hostRow(id)]})}if(idx===-1)return i.reply({content:'ℹ️ You are not entered.',ephemeral:true});g.entries.splice(idx,1);save();return i.update({embeds:[embed(g)],components:[entryRow(id),hostRow(id)]})}
if(action==='fsmm_gw_cancel'){if(i.user.id!==g.hostId&&!staff(i))return i.reply({content:'❌ Only the host or staff can cancel this event.',ephemeral:true});g.cancelled=true;g.ended=true;g.endedAt=Date.now();save();await update(client,g,[entryRow(id,true)]);await audit(client,g,`Event **${g.id}** cancelled by <@${i.user.id}>.`);return i.reply({content:'✅ Event cancelled.',ephemeral:true})}
if(action==='fsmm_gw_finish'){if(i.user.id!==g.hostId&&!staff(i))return i.reply({content:'❌ Only the host or staff can control this event.',ephemeral:true});if(!g.ended){g.ended=true;g.endedAt=Date.now();save();await update(client,g,[entryRow(id,true),hostRow(id,true)]);await announce(client,g,`🏁 **${clean(g.prize,250)}** is ready for transparent winner review.`)}if(!g.entries.length)return i.reply({content:'❌ No eligible entries.',ephemeral:true});const modal=new ModalBuilder().setCustomId(`fsmm_gw_winner:${id}`).setTitle('Declare Winner');const ids=new TextInputBuilder().setCustomId('winner_ids').setLabel(`Winner user IDs (${g.winners})`).setPlaceholder('Paste Discord user IDs separated by commas').setStyle(TextInputStyle.Short).setRequired(true);const note=new TextInputBuilder().setCustomId('selection_note').setLabel('Selection note / criteria').setPlaceholder('Example: selected using the posted contest criteria').setStyle(TextInputStyle.Paragraph).setRequired(true).setMaxLength(500);modal.addComponents(new ActionRowBuilder().addComponents(ids),new ActionRowBuilder().addComponents(note));return i.showModal(modal)}}
async function modal(client,i){const id=i.customId.split(':')[1],g=state.giveaways[id];if(!g)return i.reply({content:'❌ Event not found.',ephemeral:true});if(i.user.id!==g.hostId&&!staff(i))return i.reply({content:'❌ Only the host or staff can declare winners.',ephemeral:true});const ids=[...new Set(i.fields.getTextInputValue('winner_ids').split(/[ ,\n]+/).map(x=>x.trim()).filter(Boolean))];const note=clean(i.fields.getTextInputValue('selection_note'),500);if(ids.length!==g.winners)return i.reply({content:`❌ Enter exactly ${g.winners} winner ID${g.winners>1?'s':''}.`,ephemeral:true});if(ids.some(x=>!g.entries.includes(x)))return i.reply({content:'❌ Every winner must be an eligible entrant.',ephemeral:true});const members=[];for(const id of ids){const m=await i.guild.members.fetch(id).catch(()=>null);if(!m)return i.reply({content:`❌ <@${id}> is no longer in the server.`,ephemeral:true});if(g.requiredRoleId&&!m.roles.cache.has(g.requiredRoleId))return i.reply({content:`❌ <@${id}> no longer has the required role.`,ephemeral:true});members.push(m)}g.winnerIds=ids;g.selectedAt=Date.now();g.selectedBy=i.user.id;g.selectionNote=note;save();await announce(client,g,`🎉 **REWARD EVENT RESULT**\nReward: **${clean(g.prize,250)}**\nWinner${ids.length>1?'s':''}: ${ids.map(x=>`<@${x}>`).join(', ')}\nSelected by: <@${i.user.id}>\nCriteria note: ${note}`);await update(client,g,[entryRow(id,true)]);await audit(client,g,`Event **${g.id}** winner declaration by <@${i.user.id}>.\n**Winner${ids.length>1?'s':''}:** ${ids.map(x=>`<@${x}>`).join(', ')}\n**Note:** ${note}`);return i.reply({content:'✅ Winner declaration saved and publicly logged.',ephemeral:true})}
function patchClient(){const proto=Client.prototype,old=proto.emit;proto.emit=function(event,...args){if(event==='interactionCreate'){const i=args[0];if(i?.isChatInputCommand?.()&&i.commandName==='giveaway'){create(this,i).catch(e=>console.error('[GIVEAWAY]',e));return true}if(i?.isButton?.()&&i.customId?.startsWith('fsmm_gw_')){button(this,i).catch(e=>console.error('[GIVEAWAY]',e));return true}if(i?.isModalSubmit?.()&&i.customId?.startsWith('fsmm_gw_winner:')){modal(this,i).catch(e=>console.error('[GIVEAWAY]',e));return true}}return old.call(this,event,...args)}}
patchREST();patchClient();
const oldLogin=Client.prototype.login;Client.prototype.login=function(...args){const p=oldLogin.apply(this,args);this.once('ready',()=>Object.values(state.giveaways).forEach(g=>schedule(this,g)));return p}
