require('dotenv').config();
const fs=require('fs');const path=require('path');
const {Client,REST,PermissionFlagsBits,EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,ChannelType}=require('discord.js');
const FILE=process.env.GIVEAWAY_DATA_FILE||path.join(__dirname,'..','data','giveaways.json');
const state={giveaways:{}};
try{if(fs.existsSync(FILE))Object.assign(state,JSON.parse(fs.readFileSync(FILE,'utf8')))}catch(e){console.error('[GIVEAWAY] load:',e.message)}
function save(){fs.mkdirSync(path.dirname(FILE),{recursive:true});const t=FILE+'.tmp';fs.writeFileSync(t,JSON.stringify(state,null,2));fs.renameSync(t,FILE)}
function clean(v,n=1000){return String(v??'').replace(/@everyone|@here/gi,'@ mention').replace(/[\u0000-\u001F\u007F]/g,' ').trim().slice(0,n)||''}
function staff(i){return !!i.guild&&(i.guild.ownerId===i.user.id||i.memberPermissions?.has(PermissionFlagsBits.ManageGuild)||i.memberPermissions?.has(PermissionFlagsBits.ManageMessages)||i.member?.roles?.cache?.some(r=>['FSMM Staff','Owner','Moderator'].includes(r.name)))}
function parseDuration(v){const s=String(v||'').trim().toLowerCase();const m=s.match(/^(\d+(?:\.\d+)?)\s*(s|m|h|d|w)$/);if(!m)return null;const mult={s:1000,m:60000,h:3600000,d:86400000,w:604800000};const ms=Number(m[1])*mult[m[2]];return Number.isFinite(ms)&&ms>=60000&&ms<=30*86400000?ms:null}
function validUrl(v){try{const u=new URL(String(v));return ['http:','https:'].includes(u.protocol)?u.toString():null}catch{return null}}
function id(){return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`}
function entryRow(g){return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`fsmm_gw_join:${g.id}`).setLabel(g.ended?'Event Ended':'Enter Giveaway').setEmoji('🎉').setStyle(ButtonStyle.Success).setDisabled(!!g.ended),new ButtonBuilder().setCustomId(`fsmm_gw_leave:${g.id}`).setLabel('Leave').setEmoji('🚪').setStyle(ButtonStyle.Secondary).setDisabled(!!g.ended))}
function controlRow(g){return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`fsmm_gw_end:${g.id}`).setLabel('End Giveaway').setEmoji('⏹️').setStyle(ButtonStyle.Primary).setDisabled(!!g.ended),new ButtonBuilder().setCustomId(`fsmm_gw_cancel:${g.id}`).setLabel('Cancel').setEmoji('🗑️').setStyle(ButtonStyle.Danger).setDisabled(!!g.ended))}
function embed(g){const end=g.ended?`Ended <t:${Math.floor((g.endedAt||Date.now())/1000)}:R>`:`Ends <t:${Math.floor(g.endsAt/1000)}:R>`;let d=`## ${clean(g.prize,250)}\n\n🎟️ **Entries:** ${g.entries.length}\n🏆 **Winners:** ${g.winnerIds?.length?g.winnerIds.map(x=>`<@${x}>`).join(', '):'Pending'}\n⏱️ **${end}**`;if(g.requiredRoleId)d+=`\n🔒 **Required role:** <@&${g.requiredRoleId}>`;if(g.description)d+=`\n\n${clean(g.description,1500)}`;const e=new EmbedBuilder().setTitle(clean(g.title,256)||'🎉 FSMM GIVEAWAY').setDescription(d).setColor(g.color||0x5865f2).setFooter({text:clean(g.footer,200)||`Hosted by ${g.hostTag} • FSMM`}).setTimestamp(new Date(g.createdAt));if(g.thumbnail)e.setThumbnail(g.thumbnail);if(g.image)e.setImage(g.image);return e}
async function fetchMsg(client,g){const ch=await client.channels.fetch(g.channelId).catch(()=>null);if(!ch?.isTextBased())return null;return ch.messages.fetch(g.messageId).catch(()=>null)}
async function update(client,g,ended=false){const m=await fetchMsg(client,g);if(!m)return;await m.edit({embeds:[embed(g)],components:ended?[entryRow(g)]:[entryRow(g),controlRow(g)]}).catch(()=>null)}
async function announce(client,g,text){const ch=await client.channels.fetch(g.channelId).catch(()=>null);if(ch?.isTextBased())await ch.send({content:clean(text,1900)}).catch(()=>null)}
async function finish(client,g,reason='timer'){if(g.ended)return;g.ended=true;g.endedAt=Date.now();g.endReason=reason;save();await update(client,g,true);if(g.silentEnd)return;await announce(client,g,g.endMessage||`🏁 **Giveaway ended!**\nPrize: **${clean(g.prize,250)}**\nEligible entries: **${g.entries.length}**\n🏆 **${g.winners} winner${g.winners===1?'':'s'} must be selected manually by the host/staff using /giveaway winner.`)}
function schedule(client,g){if(g.ended||g.cancelled)return;const wait=Math.max(1000,g.endsAt-Date.now());setTimeout(()=>finish(client,g).catch(e=>console.error('[GIVEAWAY] finish:',e.message)),wait)}
function optionsCreate(){return [
 {type:3,name:'duration',description:'Duration: 30m, 2h, 1d (1m–30d)',required:true},
 {type:3,name:'prize',description:'The giveaway prize',required:true},
 {type:4,name:'winners',description:'Number of winners (1–20)',required:false,min_value:1,max_value:20},
 {type:7,name:'channel',description:'Channel where the giveaway is posted',required:false,channel_types:[ChannelType.GuildText,ChannelType.GuildAnnouncement]},
 {type:8,name:'required_role',description:'Role required to enter',required:false},
 {type:8,name:'winner_role',description:'Role granted to selected winners',required:false},
 {type:3,name:'title',description:'Custom embed title',required:false,max_length:256},
 {type:3,name:'description',description:'Custom giveaway description',required:false,max_length:1500},
 {type:3,name:'image',description:'Large embed image URL',required:false},
 {type:3,name:'thumbnail',description:'Small embed thumbnail URL',required:false},
 {type:3,name:'color',description:'Embed color: hex like #5865F2',required:false},
 {type:3,name:'entry_message',description:'Message sent when the giveaway is created',required:false,max_length:1500},
 {type:3,name:'end_message',description:'Custom message sent when it ends',required:false,max_length:1500},
 {type:3,name:'winner_dm',description:'Optional DM sent to each selected winner',required:false,max_length:1000},
 {type:3,name:'winner_announcement',description:'Custom public winner announcement',required:false,max_length:1500},
 {type:5,name:'mention_winners',description:'Mention winners in the announcement',required:false},
 {type:5,name:'mention_required_role',description:'Mention required role',required:false},
 {type:3,name:'footer',description:'Custom embed footer',required:false,max_length:200},
 {type:5,name:'allow_host_entry',description:'Allow the host to enter',required:false},
 {type:5,name:'silent_end',description:'Do not send the automatic end notice',required:false}
]}
function buildCommand(){return {name:'giveaway',description:'Professional FSMM giveaway management',default_member_permissions:PermissionFlagsBits.ManageGuild.toString(),options:[
 {type:1,name:'create',description:'Create a professional giveaway',options:optionsCreate()},
 {type:1,name:'end',description:'End a giveaway early',options:[{type:3,name:'id',description:'Giveaway ID',required:true}]},
 {type:1,name:'cancel',description:'Cancel a giveaway',options:[{type:3,name:'id',description:'Giveaway ID',required:true}]},
 {type:1,name:'winner',description:'Declare a winner manually from eligible entries',options:[{type:3,name:'id',description:'Giveaway ID',required:true},{type:6,name:'user',description:'Eligible winner',required:true}]},
 {type:1,name:'reroll',description:'Replace the last selected winner manually',options:[{type:3,name:'id',description:'Giveaway ID',required:true},{type:6,name:'user',description:'Replacement eligible winner',required:true}]},
 {type:1,name:'edit',description:'Edit a live giveaway',options:[{type:3,name:'id',description:'Giveaway ID',required:true},{type:3,name:'prize',description:'New prize',required:false},{type:3,name:'title',description:'New title',required:false},{type:3,name:'description',description:'New description',required:false},{type:3,name:'image',description:'New image URL',required:false},{type:3,name:'thumbnail',description:'New thumbnail URL',required:false}]},
 {type:1,name:'list',description:'List active FSMM giveaways'},
 {type:1,name:'info',description:'View giveaway details',options:[{type:3,name:'id',description:'Giveaway ID',required:true}]}
]}}
function patchREST(){const old=REST.prototype.put;REST.prototype.put=function(route,opts,...rest){try{if(opts?.body&&Array.isArray(opts.body))opts={...opts,body:opts.body.map(c=>c?.name==='giveaway'?buildCommand():c)}}catch(e){console.error('[GIVEAWAY] command patch:',e.message)}return old.call(this,route,opts,...rest)}}
async function create(client,i){if(!staff(i))return i.reply({content:'❌ Staff only.',ephemeral:true});const o=i.options,ms=parseDuration(o.getString('duration',true));if(!ms)return i.reply({content:'❌ Invalid duration. Use values like `30m`, `2h`, `1d`. Maximum is 30 days.',ephemeral:true});const prize=clean(o.getString('prize',true),250);const image=validUrl(o.getString('image')),thumbnail=validUrl(o.getString('thumbnail'));if(o.getString('image')&&!image||o.getString('thumbnail')&&!thumbnail)return i.reply({content:'❌ Image/thumbnail must be a valid http(s) URL.',ephemeral:true});let color=0x5865f2;const rawColor=o.getString('color');if(rawColor){const x=rawColor.replace(/^#/,'');if(!/^[0-9a-f]{6}$/i.test(x))return i.reply({content:'❌ Color must be a 6-digit hex value like `#5865F2`.',ephemeral:true});color=parseInt(x,16)}const channel=o.getChannel('channel')||i.channel;const role=o.getRole('required_role'),winnerRole=o.getRole('winner_role');const idv=id();const g={id:idv,guildId:i.guild.id,channelId:channel.id,prize,winners:o.getInteger('winners')||1,requiredRoleId:role?.id||null,winnerRoleId:winnerRole?.id||null,hostId:i.user.id,hostTag:i.user.tag,createdAt:Date.now(),endsAt:Date.now()+ms,entries:[],winnerIds:[],ended:false,cancelled:false,title:clean(o.getString('title'),256),description:clean(o.getString('description'),1500),image,thumbnail,color,entryMessage:clean(o.getString('entry_message'),1500),endMessage:clean(o.getString('end_message'),1500),winnerDM:clean(o.getString('winner_dm'),1000),winnerAnnouncement:clean(o.getString('winner_announcement'),1500),mentionWinners:o.getBoolean('mention_winners')||false,mentionRequiredRole:o.getBoolean('mention_required_role')||false,footer:clean(o.getString('footer'),200),allowHostEntry:o.getBoolean('allow_host_entry')||false,silentEnd:o.getBoolean('silent_end')||false};const m=await channel.send({embeds:[embed(g)],components:[entryRow(g),controlRow(g)]});g.messageId=m.id;state.giveaways[idv]=g;save();schedule(client,g);if(g.entryMessage)await announce(client,g,g.entryMessage);return i.reply({content:`✅ Giveaway created.\n🆔 ID: \`${idv}\`\n📍 ${channel}\n🎁 **${prize}**\n⏱️ **${o.getString('duration',true)}**\n🏆 Winners: **${g.winners}**`,ephemeral:true})}
function find(i){const idv=i.options.getString('id',true),g=state.giveaways[idv];return g&&g.guildId===i.guild.id?g:null}
async function endCmd(client,i){const g=find(i);if(!g)return i.reply({content:'❌ Giveaway not found.',ephemeral:true});if(!staff(i)&&i.user.id!==g.hostId)return i.reply({content:'❌ Host/staff only.',ephemeral:true});await finish(client,g,'manual');return i.reply({content:'✅ Giveaway ended. Use /giveaway winner to declare the winner manually.',ephemeral:true})}
async function cancelCmd(client,i){const g=find(i);if(!g)return i.reply({content:'❌ Giveaway not found.',ephemeral:true});if(!staff(i)&&i.user.id!==g.hostId)return i.reply({content:'❌ Host/staff only.',ephemeral:true});g.cancelled=true;g.ended=true;g.endedAt=Date.now();save();const m=await fetchMsg(client,g);if(m)await m.edit({embeds:[embed(g)],components:[]}).catch(()=>null);await announce(client,g,`🛑 **Giveaway cancelled.** ID: ${g.id}`);return i.reply({content:'✅ Giveaway cancelled.',ephemeral:true})}
async function winnerCmd(client,i,replace=false){const g=find(i);if(!g)return i.reply({content:'❌ Giveaway not found.',ephemeral:true});if(!staff(i)&&i.user.id!==g.hostId)return i.reply({content:'❌ Host/staff only.',ephemeral:true});if(!g.ended)return i.reply({content:'❌ End the giveaway first.',ephemeral:true});const u=i.options.getUser('user',true);if(!g.entries.includes(u.id))return i.reply({content:'❌ That user is not an eligible entry.',ephemeral:true});if(replace){if(!g.winnerIds?.length)return i.reply({content:'❌ There is no existing winner to replace.',ephemeral:true});g.winnerIds[g.winnerIds.length-1]=u.id}else{if(g.winnerIds.includes(u.id))return i.reply({content:'❌ That user is already a winner.',ephemeral:true});if(g.winnerIds.length>=g.winners)return i.reply({content:`❌ All ${g.winners} winner slots are filled. Use /giveaway reroll to replace the last selected winner.`,ephemeral:true});g.winnerIds.push(u.id)}g.selectedBy=i.user.id;g.selectedAt=Date.now();save();if(g.winnerRoleId){const member=await i.guild.members.fetch(u.id).catch(()=>null);if(member)await member.roles.add(g.winnerRoleId).catch(()=>null)}if(g.winnerDM){const member=await i.guild.members.fetch(u.id).catch(()=>null);if(member)await member.send(clean(g.winnerDM.replaceAll('{prize}',g.prize).replaceAll('{winner}',u.toString()),1000)).catch(()=>null)}const winners=g.winnerIds.map(x=>`<@${x}>`).join(', ');const publicText=g.winnerAnnouncement?g.winnerAnnouncement.replaceAll('{prize}',g.prize).replaceAll('{winner}',u.toString()).replaceAll('{winners}',winners):`🎉 **Winner${g.winnerIds.length>1?'s':''} selected!**\nPrize: **${clean(g.prize,250)}**\nWinner${g.winnerIds.length>1?'s':''}: ${winners}\n\nSelected manually by <@${i.user.id}>.`;await announce(client,g,publicText);return i.reply({content:`✅ ${replace?'Winner replaced':'Winner declared'}: ${u.tag}.\n🔎 Eligible entry verified.\n👤 Selected by: ${i.user.tag}`,ephemeral:true})}
async function editCmd(client,i){const g=find(i);if(!g)return i.reply({content:'❌ Giveaway not found.',ephemeral:true});if(!staff(i)&&i.user.id!==g.hostId)return i.reply({content:'❌ Host/staff only.',ephemeral:true});if(g.ended)return i.reply({content:'❌ Cannot edit an ended giveaway.',ephemeral:true});const o=i.options;const changes={prize:o.getString('prize'),title:o.getString('title'),description:o.getString('description'),image:o.getString('image'),thumbnail:o.getString('thumbnail')};for(const [k,v] of Object.entries(changes))if(v!==null){if((k==='image'||k==='thumbnail')&&!validUrl(v))return i.reply({content:`❌ ${k} must be a valid http(s) URL.`,ephemeral:true});g[k]=k==='image'||k==='thumbnail'?validUrl(v):clean(v,1500)}save();await update(client,g);return i.reply({content:'✅ Giveaway updated.',ephemeral:true})}
async function listCmd(i){const a=Object.values(state.giveaways).filter(g=>g.guildId===i.guild.id&&!g.ended&&!g.cancelled);return i.reply({embeds:[new EmbedBuilder().setTitle('🎉 Active FSMM Giveaways').setColor(0x5865f2).setDescription(a.length?a.map(g=>`• \`${g.id}\` — **${clean(g.prize,150)}** in <#${g.channelId}> — ${g.entries.length} entries — <t:${Math.floor(g.endsAt/1000)}:R>`).join('\n'):'No active giveaways.')],ephemeral:true})}
async function infoCmd(i){const g=find(i);if(!g)return i.reply({content:'❌ Giveaway not found.',ephemeral:true});return i.reply({embeds:[new EmbedBuilder().setTitle('🎉 Giveaway Info').setColor(g.color).setDescription(`**ID:** \`${g.id}\`\n**Prize:** ${clean(g.prize,250)}\n**Entries:** ${g.entries.length}\n**Winners:** ${g.winners}\n**Selected:** ${g.winnerIds?.length||0}\n**Host:** <@${g.hostId}>\n**Channel:** <#${g.channelId}>\n**Status:** ${g.cancelled?'Cancelled':g.ended?'Ended':'Active'}`)],ephemeral:true})}
function patchClient(){const old=Client.prototype.emit;Client.prototype.emit=function(event,...args){if(event==='interactionCreate'){const i=args[0];if(i?.isChatInputCommand?.()&&i.commandName==='giveaway'){const sub=i.options.getSubcommand(false);(async()=>{if(sub==='create')return create(this,i);if(sub==='end')return endCmd(this,i);if(sub==='cancel')return cancelCmd(this,i);if(sub==='winner')return winnerCmd(this,i,false);if(sub==='reroll')return winnerCmd(this,i,true);if(sub==='edit')return editCmd(this,i);if(sub==='list')return listCmd(i);if(sub==='info')return infoCmd(i);return i.reply({content:'Use /giveaway create to create one.',ephemeral:true})})().catch(e=>{console.error('[GIVEAWAY]',e);if(!i.replied&&!i.deferred)i.reply({content:'❌ Giveaway command failed.',ephemeral:true}).catch(()=>null)});return true}if(i?.isButton?.()&&i.customId?.startsWith('fsmm_gw_')){(async()=>{const [a,idv]=i.customId.split(':');const g=state.giveaways[idv];if(!g)return i.reply({content:'❌ Giveaway not found.',ephemeral:true});if(a==='fsmm_gw_join'||a==='fsmm_gw_leave'){if(g.ended||g.cancelled)return i.reply({content:'❌ This giveaway is closed.',ephemeral:true});if(g.requiredRoleId&&!i.member.roles.cache.has(g.requiredRoleId))return i.reply({content:'❌ You do not have the required role.',ephemeral:true});const idx=g.entries.indexOf(i.user.id);if(a==='fsmm_gw_join'){if(idx!==-1)return i.reply({content:'ℹ️ You are already entered.',ephemeral:true});if(i.user.id===g.hostId&&!g.allowHostEntry)return i.reply({content:'❌ The host cannot enter this giveaway.',ephemeral:true});g.entries.push(i.user.id);save();return i.update({embeds:[embed(g)],components:[entryRow(g),controlRow(g)]})}if(idx===-1)return i.reply({content:'ℹ️ You are not entered.',ephemeral:true});g.entries.splice(idx,1);save();return i.update({embeds:[embed(g)],components:[entryRow(g),controlRow(g)])}if(a==='fsmm_gw_end'){if(!staff(i)&&i.user.id!==g.hostId)return i.reply({content:'❌ Host/staff only.',ephemeral:true});await finish(this,g,'button');return i.reply({content:'✅ Giveaway ended. Winners must be declared manually.',ephemeral:true})}if(a==='fsmm_gw_cancel'){if(!staff(i)&&i.user.id!==g.hostId)return i.reply({content:'❌ Host/staff only.',ephemeral:true});g.cancelled=true;g.ended=true;g.endedAt=Date.now();save();await update(this,g,true);return i.reply({content:'✅ Giveaway cancelled.',ephemeral:true})}})().catch(e=>console.error('[GIVEAWAY BUTTON]',e));return true}return old.call(this,event,...args)}}
patchREST();patchClient();
const oldLogin=Client.prototype.login;Client.prototype.login=function(...args){const p=oldLogin.apply(this,args);this.once('ready',()=>Object.values(state.giveaways).forEach(g=>schedule(this,g)));return p}
