require('dotenv').config();const fs=require('fs');const path=require('path');const{Client,GatewayIntentBits,REST,Routes,SlashCommandBuilder,EmbedBuilder,PermissionFlagsBits,ActionRowBuilder,StringSelectMenuBuilder,ButtonBuilder,ButtonStyle,ChannelType,ModalBuilder,TextInputBuilder,TextInputStyle,MessageFlags,AttachmentBuilder}=require('discord.js');const TOKEN=process.env.DISCORD_TOKEN,CLIENT_ID=process.env.CLIENT_ID,GUILD_ID=process.env.GUILD_ID;if(!TOKEN||!CLIENT_ID||!GUILD_ID)throw new Error('Missing DISCORD_TOKEN, CLIENT_ID or GUILD_ID');
const DATA_FILE=process.env.DATA_FILE||path.join(__dirname,'..','data','store.json');const CATEGORY='🎫 FSMM SERVICES',LOGS='fsmm-logs';
const ROLES={owner:'1466090947170406617',mod:'1466085137459712114',staff:'1466088151331242015',painter:'1466245073820844211',middleman:'1466091035510706262'};
const ROLE_NAMES={owner:'Owner',staff:'FSMM Staff',painter:'FSMM Base Painter',middleman:'FSMM Middleman'};
const BASES=['Candy','Lava','Galaxy','Yin Yang','Radioactive','Cursed','Divine','Cyber','Phantom','Crystal'];const MM=[['10M - 250M','💰'],['250M - 500M','💵'],['500M - 1B','🤑'],['1B - 5B','💎'],['5B+','👑'],['OG / Rare Items','🐱']];const SUPPORT=[['Host a Giveaway','host_gw'],['Claim a Giveaway','claim_gw'],['Report','report'],['Apply for a Role','role_apply']];
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMessages,GatewayIntentBits.GuildMembers]});let store={vouches:[],warnings:{},messages:{},commands:{}};let dirty=false;
try{if(fs.existsSync(DATA_FILE))store={...store,...JSON.parse(fs.readFileSync(DATA_FILE,'utf8'))}}catch(e){console.error('[DATA]',e.message)}
function save(){try{fs.mkdirSync(path.dirname(DATA_FILE),{recursive:true});const t=DATA_FILE+'.tmp';fs.writeFileSync(t,JSON.stringify(store,null,2));fs.renameSync(t,DATA_FILE);dirty=false}catch(e){console.error('[SAVE]',e.message)}}setInterval(()=>dirty&&save(),10000).unref();
const clean=(v,n=900)=>String(v??'').replace(/@everyone|@here/gi,'@ mention').replace(/[\u0000-\u001F\u007F]/g,' ').trim().slice(0,n)||'Not provided';const E=(t,d='')=>new EmbedBuilder().setTitle(t).setDescription(d).setColor(0x5865f2).setFooter({text:'FSMM'});const R=(...x)=>new ActionRowBuilder().addComponents(...x);
function staff(i){return!!i.guild&&(i.guild.ownerId===i.user.id||i.memberPermissions?.has(PermissionFlagsBits.ManageGuild)||i.member?.roles?.cache?.has(ROLES.staff)||i.member?.roles?.cache?.has(ROLES.mod))}function owner(i){return!!i.guild&&(i.guild.ownerId===i.user.id||i.member?.roles?.cache?.has(ROLES.owner))}
function findRole(g,id,name){return g.roles.cache.get(id)||g.roles.cache.find(r=>r.name===name)}
async function setup(g){let s=findRole(g,ROLES.staff,ROLE_NAMES.staff),m=findRole(g,ROLES.middleman,ROLE_NAMES.middleman),p=findRole(g,ROLES.painter,ROLE_NAMES.painter),o=findRole(g,ROLES.owner,ROLE_NAMES.owner);if(!s)s=await g.roles.create({name:ROLE_NAMES.staff});if(!m)m=await g.roles.create({name:ROLE_NAMES.middleman});if(!p)p=await g.roles.create({name:ROLE_NAMES.painter});if(!o)o=await g.roles.create({name:ROLE_NAMES.owner});let c=g.channels.cache.find(x=>x.type===ChannelType.GuildCategory&&x.name===CATEGORY);if(!c)c=await g.channels.create({name:CATEGORY,type:ChannelType.GuildCategory});let l=g.channels.cache.find(x=>x.type===ChannelType.GuildText&&x.name===LOGS);if(!l)l=await g.channels.create({name:LOGS,type:ChannelType.GuildText,permissionOverwrites:[{id:g.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel]},{id:s.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages]},{id:o.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages]}]});return{s,m,p,o,c,l}}
async function log(g,t,d){try{const{x}=await Promise.resolve({x:(await setup(g)).l});await x.send({embeds:[E('🛡️ '+t,d)]})}catch(e){console.error('[LOG]',e.message)}}
function btn(claim=false){return R(new ButtonBuilder().setCustomId('fsmm_claim').setLabel(claim?'Ticket Claimed':'Claim Ticket').setStyle(claim?ButtonStyle.Secondary:ButtonStyle.Primary).setDisabled(claim),new ButtonBuilder().setCustomId('fsmm_close').setLabel('Close Ticket').setStyle(ButtonStyle.Danger))}
function menu(id,arr){return R(new StringSelectMenuBuilder().setCustomId(id).setPlaceholder('Select an option').addOptions(arr.map(x=>{const label=Array.isArray(x)?x[0]:x;const emoji=Array.isArray(x)?x[1]:undefined;return{label,value:label,description:label,...(emoji?{emoji}: {})}})))}
function supportMenu(){return R(new StringSelectMenuBuilder().setCustomId('fsmm_support').setPlaceholder('🛟 Select support type').addOptions(SUPPORT.map(([l,v])=>({label:l,value:v,description:l}))))}
async function panel(g,name,e,components){const s=await setup(g);let c=g.channels.cache.find(x=>x.type===ChannelType.GuildText&&x.name===name);if(!c)c=await g.channels.create({name,type:ChannelType.GuildText,parent:s.c.id});const old=(await c.messages.fetch({limit:20})).find(m=>m.author.id===client.user.id&&m.components.length);if(old)await old.edit({embeds:[e],components:[components]});else await c.send({embeds:[e],components:[components]})}
async function panels(g){await panel(g,'🤝・middleman',E('🤝 FSMM MIDDLEMAN','Choose the trade value.'),menu('fsmm_mm',MM));await panel(g,'🛟・support',E('🛟 FSMM SUPPORT','Choose Host a Giveaway, Claim a Giveaway, Report, or Apply for a Role.'),supportMenu());await panel(g,'🎨・base-painting',E('🎨 FSMM BASE PAINTING','Choose a base.'),menu('fsmm_base',BASES))}
function input(id,label,style=TextInputStyle.Short,required=true,max=900){return new TextInputBuilder().setCustomId(id).setLabel(label).setStyle(style).setRequired(required).setMaxLength(max)}
function countTickets(g,u){const c=g.channels.cache.find(x=>x.type===ChannelType.GuildCategory&&x.name===CATEGORY);return c?c.children.cache.filter(x=>x.topic?.includes('FSMM_USER:'+u)).size:0}
async function ticket(i,type,data){if(countTickets(i.guild,i.user.id)>=3)return i.editReply({content:'❌ You already have 3 open tickets.'});const r=await setup(i.guild),team=type==='middleman'?r.m:type==='base-painting'?r.p:r.s,slug=type==='middleman'?'middleman':type==='base-painting'?'base-painting':'support';const name=(i.user.username.replace(/[^a-z0-9-]/gi,'').slice(0,55)||i.user.id).toLowerCase();const c=await i.guild.channels.create({name:`${slug}-${name}`.slice(0,95),type:ChannelType.GuildText,parent:r.c.id,topic:`FSMM_USER:${i.user.id} TYPE:${type}`,permissionOverwrites:[{id:i.guild.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel]},{id:i.user.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]},{id:r.s.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]},{id:team.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]}]});await c.send({content:`<@${i.user.id}> <@&${team.id}>`,allowedMentions:{users:[i.user.id],roles:[team.id]},embeds:[E('🎫 FSMM '+type.toUpperCase()+' TICKET',Object.entries(data).map(([k,v])=>`**${k}:** ${clean(v,600)}`).join('\n'))],components:[btn()]});await i.editReply({content:`✅ Ticket created: ${c}`});log(i.guild,'TICKET OPENED',`**Ticket:** ${c}\n**User:** <@${i.user.id}>`)}
function commands(){const a=[['ping','Check latency'],['help','Show commands'],['setup','Create FSMM panels'],['ticket','Create FSMM panels'],['membercount','Show member count'],['vouch','Add a vouch'],['vouches','Show vouches'],['leaderboard','Vouch leaderboard'],['stats','Show stats'],['transcript','Create transcript'],['warn','Warn member'],['warnings','Show warnings'],['ban','Ban member'],['unban','Unban user'],['kick','Kick member'],['timeout','Timeout member'],['untimeout','Remove timeout'],['clear','Delete messages'],['announce','Send announcement'],['giveaway','Start giveaway']];return a.map(([n,d])=>new SlashCommandBuilder().setName(n).setDescription(d).toJSON())}
function addOpts(){return{user:o=>o.addUserOption(x=>x.setName('user').setDescription('User').setRequired(true)),reason:o=>o.addStringOption(x=>x.setName('reason').setDescription('Reason').setRequired(false))}}
async function register(){const rest=new REST({version:'10'}).setToken(TOKEN);const body=commands();const map=new Map(body.map(x=>[x.name,x]));const edit=(n,fn)=>{const x=map.get(n);if(x)fn(x)};edit('vouch',x=>{x.options=[{type:6,name:'user',description:'User',required:true},{type:3,name:'service',description:'Service',required:true}]});edit('vouches',x=>{x.options=[{type:6,name:'user',description:'User',required:false}]});edit('stats',x=>{x.options=[{type:6,name:'user',description:'User',required:false}]});edit('warn',x=>{x.default_member_permissions=PermissionFlagsBits.ModerateMembers.toString();x.options=[{type:6,name:'user',description:'Member',required:true},{type:3,name:'reason',description:'Reason',required:true}]});edit('warnings',x=>{x.options=[{type:6,name:'user',description:'Member',required:true}]});edit('ban',x=>{x.default_member_permissions=PermissionFlagsBits.BanMembers.toString();x.options=[{type:6,name:'user',description:'Member',required:true},{type:3,name:'reason',description:'Reason',required:false}]});edit('unban',x=>{x.default_member_permissions=PermissionFlagsBits.BanMembers.toString();x.options=[{type:3,name:'user_id',description:'User ID',required:true}]});edit('kick',x=>{x.default_member_permissions=PermissionFlagsBits.KickMembers.toString();x.options=[{type:6,name:'user',description:'Member',required:true},{type:3,name:'reason',description:'Reason',required:false}]});edit('timeout',x=>{x.default_member_permissions=PermissionFlagsBits.ModerateMembers.toString();x.options=[{type:6,name:'user',description:'Member',required:true},{type:4,name:'minutes',description:'Minutes',required:true,min_value:1,max_value:40320}]});edit('untimeout',x=>{x.options=[{type:6,name:'user',description:'Member',required:true}]});edit('clear',x=>{x.default_member_permissions=PermissionFlagsBits.ManageMessages.toString();x.options=[{type:4,name:'amount',description:'1-100',required:true,min_value:1,max_value:100}]});edit('announce',x=>{x.options=[{type:3,name:'message',description:'Message',required:true}]});edit('giveaway',x=>{x.options=[{type:4,name:'minutes',description:'Minutes',required:true,min_value:1,max_value:10080},{type:3,name:'prize',description:'Prize',required:true}]});await rest.put(Routes.applicationGuildCommands(CLIENT_ID,GUILD_ID),{body:[...map.values()]});console.log('[FSMM] commands registered:',map.size)}
async function transcript(i){const ms=await i.channel.messages.fetch({limit:100});const txt=[...ms.values()].reverse().map(m=>`[${m.createdAt.toISOString()}] ${m.author.tag}: ${clean(m.content,2000)}`).join('\n');return i.editReply({content:'📄 Transcript',files:[new AttachmentBuilder(Buffer.from(txt||'No messages'),{name:`transcript-${Date.now()}.txt`})]})}
client.once('ready',async()=>{console.log('[FSMM] ONLINE',client.user.tag);try{await register()}catch(e){console.error('[REGISTER]',e)}});
client.on('interactionCreate',async i=>{try{
if(i.isChatInputCommand()){store.commands[i.commandName]=(store.commands[i.commandName]||0)+1;dirty=true;const n=i.commandName;const slow=['setup','ticket','transcript','warn','warnings','ban','unban','kick','timeout','untimeout','clear','announce','giveaway'];if(slow.includes(n))await i.deferReply({flags:MessageFlags.Ephemeral});
if(n==='ping')return i.reply({content:`🏓 Pong! ${client.ws.ping}ms`,flags:MessageFlags.Ephemeral});if(n==='help')return i.reply({content:'FSMM: /setup /ticket /vouch /vouches /leaderboard /stats /transcript /warn /warnings /ban /unban /kick /timeout /untimeout /clear /announce /giveaway',flags:MessageFlags.Ephemeral});if(n==='membercount')return i.reply({content:`👥 ${i.guild.memberCount} members`,flags:MessageFlags.Ephemeral});if(n==='setup'||n==='ticket'){if(!staff(i))return i.editReply({content:'❌ Staff only.'});await panels(i.guild);return i.editReply({content:'✅ Panels updated.'})}
if(n==='vouch'){const u=i.options.getUser('user',true),s=i.options.getString('service',true);store.vouches.push({from:i.user.id,to:u.id,service:clean(s,200),at:Date.now()});dirty=true;return i.reply({content:`⭐ Vouch added for ${u.tag}.`,flags:MessageFlags.Ephemeral})}if(n==='vouches'){const u=i.options.getUser('user')||i.user,v=store.vouches.filter(x=>x.to===u.id);return i.reply({embeds:[E('⭐ Vouches for '+u.tag,v.length?v.slice(-10).map(x=>`<@${x.from}> — ${clean(x.service,150)}`).join('\n'):'No vouches yet.')],flags:MessageFlags.Ephemeral})}if(n==='leaderboard'){const c={};for(const v of store.vouches)c[v.to]=(c[v.to]||0)+1;const top=Object.entries(c).sort((a,b)=>b[1]-a[1]).slice(0,10);return i.reply({embeds:[E('🏆 VOUCH LEADERBOARD',top.length?top.map(([id,x],z)=>`**${z+1}.** <@${id}> — ${x}`).join('\n'):'No vouches yet.')],flags:MessageFlags.Ephemeral})}if(n==='stats'){const u=i.options.getUser('user')||i.user;return i.reply({embeds:[E('📊 Stats — '+u.tag,`⭐ Vouches: ${store.vouches.filter(x=>x.to===u.id).length}\n💬 Messages: ${store.messages[u.id]||0}`)],flags:MessageFlags.Ephemeral})}if(n==='transcript'){if(!staff(i)||!i.channel?.topic?.includes('FSMM_USER:'))return i.editReply({content:'❌ Staff only and must be inside an FSMM ticket.'});return transcript(i)}
if(n==='warn'){const u=i.options.getUser('user',true),r=i.options.getString('reason',true);store.warnings[u.id]=store.warnings[u.id]||[];store.warnings[u.id].push({by:i.user.id,reason:clean(r,500),at:Date.now()});dirty=true;return i.editReply({content:`⚠️ Warned ${u.tag}.`})}if(n==='warnings'){const u=i.options.getUser('user',true),w=store.warnings[u.id]||[];return i.editReply({embeds:[E('⚠️ Warnings — '+u.tag,w.length?w.map((x,z)=>`${z+1}. ${clean(x.reason,250)} — <@${x.by}>`).join('\n'):'No warnings.')]})}if(n==='ban'){const u=i.options.getUser('user',true);await i.guild.members.ban(u.id,{reason:i.options.getString('reason')||'FSMM'});return i.editReply({content:`🔨 Banned ${u.tag}.`})}if(n==='unban'){const id=i.options.getString('user_id',true);await i.guild.members.unban(id);return i.editReply({content:`✅ Unbanned ${id}.`})}if(n==='kick'){const u=i.options.getUser('user',true);await i.guild.members.kick(u.id,i.options.getString('reason')||'FSMM');return i.editReply({content:`👢 Kicked ${u.tag}.`})}if(n==='timeout'){const u=i.options.getUser('user',true),m=i.options.getInteger('minutes',true);await i.guild.members.edit(u.id,{communicationDisabledUntil:Date.now()+m*60000});return i.editReply({content:`⏳ Timed out ${u.tag} for ${m}m.`})}if(n==='untimeout'){const u=i.options.getUser('user',true);await i.guild.members.edit(u.id,{communicationDisabledUntil:null});return i.editReply({content:`✅ Timeout removed for ${u.tag}.`})}if(n==='clear'){const a=i.options.getInteger('amount',true);await i.channel.bulkDelete(a,true);return i.editReply({content:`🧹 Deleted ${a} messages.`})}if(n==='announce'){const m=clean(i.options.getString('message',true),1900);return i.channel.send({embeds:[E('📢 FSMM ANNOUNCEMENT',m)]}).then(()=>i.editReply({content:'✅ Sent.'}))}if(n==='giveaway'){const min=i.options.getInteger('minutes',true),prize=clean(i.options.getString('prize',true),300);const end=Date.now()+min*60000;const msg=await i.channel.send({embeds:[E('🎉 FSMM GIVEAWAY',`**Prize:** ${prize}\n**Ends:** <t:${Math.floor(end/1000)}:R>\nReact with 🎉 to enter.`)]});await msg.react('🎉');setTimeout(async()=>{try{const m=await i.channel.messages.fetch(msg.id);const users=await m.reactions.cache.get('🎉')?.users.fetch();const eligible=[...users.values()].filter(u=>!u.bot);const w=eligible[Math.floor(Math.random()*eligible.length)];await i.channel.send({content:w?`🎉 Winner: <@${w.id}>`:'❌ No valid entries.'})}catch(e){console.error('[GW]',e.message)}},min*60000);return i.editReply({content:'✅ Giveaway started.'})}
}
if(i.isStringSelectMenu()){if(i.customId==='fsmm_mm'){await i.deferReply({flags:MessageFlags.Ephemeral});return ticket(i,'middleman',{Value:i.values[0]})}if(i.customId==='fsmm_base'){await i.deferReply({flags:MessageFlags.Ephemeral});return ticket(i,'base-painting',{Base:i.values[0]})}if(i.customId==='fsmm_support'){await i.deferReply({flags:MessageFlags.Ephemeral});return i.editReply({content:`🛟 Selected: ${i.values[0]}`})}}
if(i.isButton()){if(i.customId==='fsmm_claim'){if(!staff(i))return i.reply({content:'❌ Staff only.',flags:MessageFlags.Ephemeral});await i.update({components:[btn(true)]});return log(i.guild,'TICKET CLAIMED',`**Ticket:** ${i.channel}\n**By:** <@${i.user.id}>`)}if(i.customId==='fsmm_close'){if(!staff(i))return i.reply({content:'❌ Staff only.',flags:MessageFlags.Ephemeral});await i.reply({content:'🔒 Closing ticket...',flags:MessageFlags.Ephemeral});setTimeout(()=>i.channel.delete().catch(()=>{}),1500)}}
}catch(e){console.error('[INTERACTION]',e);try{if(i.deferred||i.replied)await i.editReply({content:'❌ An error occurred.'});else await i.reply({content:'❌ An error occurred.',flags:MessageFlags.Ephemeral})}catch{}}});
client.on('messageCreate',m=>{if(!m.author.bot){store.messages[m.author.id]=(store.messages[m.author.id]||0)+1;dirty=true}});process.on('SIGTERM',()=>{save();client.destroy();process.exit(0)});process.on('SIGINT',()=>{save();client.destroy();process.exit(0)});client.login(TOKEN);